name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the `main` branch
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting `main` branch

jobs:
  # Job for testing
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Use the same version as in your Dockerfile

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/test_inferencing.py  # Run your unit test file